spring:
  application:
    name: damo
  datasource:
    url: jdbc:postgresql://localhost:5432/myDB
    username: postgres
    password: 412006
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password: MyVeryStrongPassword
  # configuration cache type
  cache:
    type: redis

config:
  security:
    secret: 95fb0a7b70e8e854d4f8bdbd2f1ef754b58866345824ae466813c8e2d9a9ce35
    expiration: 3600000 #ms
    refresh-token-expiration: 10800000 # 3 hours = 10800000ms
  pagination:
    base-url: http://localhost:8080/api/v1
    uri:
      product: /products/paginated
      stock: /stocks/paginated
      supplier: /suppliers/paginated
      user: /user/paginated
      order: /orders/paginated





